services:
  migrations:
    image: amchokers:latest
    network_mode: "host"
    volumes:
      - /srv/logs:/srv/logs
      - /var/www/amchokers.ru/public:/app/public
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no"
    command: migration:run:prod

  server:
    image: amchokers:latest
    network_mode: "host"
    ports:
      - "3010:3010"
    volumes:
      - /srv/logs:/srv/logs
      - /var/www/amchokers.ru/public:/app/public
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    command: start:server:prod
    depends_on:
      - migrations

  sender:
    image: amchokers:latest
    network_mode: "host"
    volumes:
      - /srv/logs:/srv/logs
      - /var/www/amchokers.ru/public:/app/public
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    command: start:sender:prod
    depends_on:
      - migrations