services:
  server:
    image: amchokers:latest
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3010:3010"
    volumes:
      - "C:/srv/logs:/srv/logs"
      - "C:/Program Files/Git/am-chokers/public:/app/public"
    command: start:server:dev

  sender:
    image: amchokers:latest
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "C:/srv/logs:/srv/logs"
      - "C:/Program Files/Git/am-chokers/public:/app/public"
    command: start:sender:dev